FROM ubuntu:18.04

RUN apt-get update --fix-missing && apt-get -y install apt-utils make zlib1g-dev build-essential ncurses-dev libbz2-dev liblzma-dev gfortran libreadline-dev libx11-dev texlive-base  libpcre3-dev libcurl4-openssl-dev libxml2-dev libssl-dev
#RUN apt-get -y install apt-utils \
#	make zlib1g-dev build-essential ncurses-dev libbz2-dev liblzma-dev \
#	linux-libc-dev  gfortran libreadline-dev libx11-dev \
	# texlive-base  libpcre3-dev libcurl4-openssl-dev \ 
	#libxml2-dev libssl-dev
